//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uventaStateApp.Resorces.Libs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        public int ID_Appeal { get; set; }
        public Nullable<int> ID_Premises { get; set; }
        public int ID_ServiceProvider { get; set; }
        public int ID_Status { get; set; }
        public string AppealMessage { get; set; }
    
        public virtual Premises Premises { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual Status Status { get; set; }
    }
}
