//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uventaStateApp.Resorces.Libs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stateUventaEntities : DbContext
    {
        public stateUventaEntities()
            : base("name=stateUventaEntities")
        {
        }

        private static stateUventaEntities _context;
        public static stateUventaEntities getContext()
        {
            if (_context == null)
            {
                _context = new stateUventaEntities();
            } return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appeal> Appeal { get; set; }
        public virtual DbSet<Build> Build { get; set; }
        public virtual DbSet<Premises> Premises { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<ServiceProvider> ServiceProvider { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
