//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uventaStateApp.Resorces.Libs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premises
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Premises()
        {
            this.Appeal = new HashSet<Appeal>();
        }
    
        public int ID_Premises { get; set; }
        public int ID_State { get; set; }
        public int ID_Build { get; set; }
        public string PremisesName { get; set; }
        public string PremisesDescription { get; set; }
        public double PremisesArea { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appeal> Appeal { get; set; }
        public virtual Build Build { get; set; }
        public virtual State State { get; set; }
    }
}
